stages:
  - build
  - test
  - lint
  - style
  - coverage
  - release

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_UPDATE_FLAGS: --jobs 2

.nix:
  tags:
    - nix

.musl:
  variables:
    DEVELOP_ARG: .#pkgsMusl.check-suite
.llvm:
  variables:
    DEVELOP_ARG: .#pkgsLLVM.check-suite

## Build stage #################################################################
build:
  stage: build
  extends: .nix
  script:
    - nix develop $DEVELOP_ARG -c meson setup build $SETUP_ARGS
    - nix develop $DEVELOP_ARG -c meson compile -C build
  artifacts:
    expire_in: 1 week
    paths:
    - 'build'

build:musl:
  extends: ["build", ".musl"]

build:llvm:
  extends: ["build", ".llvm"]

build-werror:
  extends: build
  allow_failure: true
  variables:
    SETUP_ARGS: --werror

build-werror:musl:
  extends: build-werror
  variables:
    DEVELOP_ARG: .#pkgsMusl.check-suite

build-werror:llvm:
  extends: build-werror
  variables:
    DEVELOP_ARG: .#pkgsLLVM.check-suite

dist:
  extends: build
  script:
    - "nix develop -c meson build"
    - "nix develop -c meson dist -C build --formats xztar,gztar,zip"
    - "mv build/meson-dist/* ./"
  artifacts:
    expire_in: 1 month
    paths:
      - "*.tar.xz"
      - "*.tar.gz"
      - "*.zip"

nix:
  stage: build
  extends: .nix
  script:
    - nix build

## Test stage ##################################################################
tests:
  stage: test
  extends: .nix
  needs: ["build"]
  script:
    - "nix develop $DEVELOP_ARG -c meson setup build"
    - "nix develop $DEVELOP_ARG -c meson test -C build"
  artifacts:
    expire_in: 1 week
    paths:
      - 'build'
    reports:
      junit: 'build/meson-logs/testlog.junit.xml'

tests:musl:
  extends: ["tests", ".musl"]
  needs: ["build:musl"]

tests:llvm:
  extends: ["tests", ".llvm"]
  needs: ["build:llvm"]

valgrind:memcheck:
  extends: tests
  needs: ["tests"]
  variables:
    VALGRIND: memcheck

valgrind:helgrind:
  extends: tests
  variables:
    VALGRIND: helgrind

valgrind:drd:
  extends: tests
  variables:
    VALGRIND: drd

nix-check:
  stage: test
  extends: .nix
  needs: ["nix"]
  script:
    - nix flake check

include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

## Lint stage ##################################################################
.linter:
  stage: test
  extends: .nix
  needs: []
  allow_failure: true
  before_script:
    - "nix develop -c meson setup build"

cppcheck:
  extends: .linter
  script:
    - "nix develop -c meson compile -C build ./cppcheck"

flawfinder:
  extends: .linter
  script:
    - "nix develop -c meson compile -C build ./flawfinder"

shellcheck:
  extends: .linter
  script:
    - "git ls-files '**.sh' | xargs nix develop -c shellcheck"

## Code Style stage ############################################################
.style:
  stage: style
  extends: .nix
  needs: []
  allow_failure: true

clang-format:
  extends: .style
  script:
    - "git ls-files '**.[ch]' | xargs nix develop -c clang-format -i"
    - "git diff --exit-code"

shell-format:
  extends: .style
  script:
    - "git ls-files '**.sh' | xargs nix develop -c shfmt --binary-next-line -w"
    - "git diff --exit-code"

nixfmt:
  extends: .style
  script:
    - "nix fmt"
    - "git diff --exit-code"

## Code Coverage stage #########################################################
coverage:
  stage: coverage
  extends: .nix
  needs:
    - job: tests
      artifacts: false
  script:
    - "nix develop -c meson setup -Db_coverage=true build"
    - "nix develop -c meson test -C build"
    - "nix develop -c ninja -C build coverage-html"
    - "mv build/meson-logs/coveragereport ./"
  coverage: '/lines\.\.\.\.\.\.: (\d+.\d+%)/'
  artifacts:
    expire_in: 1 month
    expose_as: 'Code Coverage'
    paths:
    - 'coveragereport/'

## Release creation ############################################################
release:
  stage: release
  image: "registry.gitlab.com/gitlab-org/release-cli:latest"
  rules:
    - if: '$CI_COMMIT_TAG'
  needs: ["dist"]
  before_script:
    - "apk update"
    - "apk add bash curl yq"
  script:
    - "bash .release.sh"
